env:
  commonjs: true
  es6: true
  jest: true
  node: true
  es2021: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false

plugins:
  - github
  - import
  - n
  - mocha

extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:n/recommended
  - plugin:import/recommended
  - plugin:mocha/recommended

overrides:
  - files: ["*.mjs"]
    parserOptions:
      ecmaVersion: latest
      sourceType: module

rules:
  {
    'camelcase': 'off',
    'eslint-comments/no-use': 'off',
    'eslint-comments/no-unused-disable': 'off',
    'i18n-text/no-en': 'off',
    'import/no-commonjs': 'off',
    'import/no-namespace': 'off',
    'no-console': 'off',
    'no-unused-vars': 'off',
    'prettier/prettier': 'error',
    'semi': 'off',
    'max-len': ['error', { 'code': 120 }],
    'mocha/no-mocha-arrows': 'off'
  }
